In [ ]:
import numpy as np
arr1=[20,40,50,70,10]
arr2=[6,2,9,7,1]
a=np.array(arr1)
b=np.array(arr2)
print(a-b)
print(a*b)
print(a/b)
print(a.dot(b))
s=4
print("Result =",a*s)



[14 38 41 63  9]
[120  80 450 490  10]
[ 3.33333333 20.          5.55555556 10.         10.        ]
1150
Result = [ 80 160 200 280  40]


In [ ]:
a=np.array([[10,20],[30,40]])
b=np.array([[3,7],[5,9]])
print(a%b)

[[1 6]
 [0 4]]


In [3]:
def my_func(x,y):
  if x>y:
    return x-y
  else:
    return x+y
import numpy as np
a1=[10,7,2]
a2=[6,5,3]
vect_func=np.vectorize(my_func)
print("Array 1:",a1)
print("Array 2:",a2)
print("Result:",vect_func(a1,a2))


Array 1: [10, 7, 2]
Array 2: [6, 5, 3]
Result: [4 2 5]
