In [ ]:
#slicing
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[2:6]
print(slice1)

[3 4 5 6]


In [ ]:
#slice with step size of 2
slice2=arr[::2]
print(slice2)

[1 3 5 7 9]


In [ ]:
#reverse the array
reverse=arr[::-1]
print(reverse)

[9 8 7 6 5 4 3 2 1]


In [ ]:
#slicing multidimensional array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
#slice row 0 to 2
#slice coloumn 1 to 3
subarray=arr[0:2,1:3]
print(subarray)


[[2 3]
 [5 6]]


In [ ]:
#extract the first coloumn
col=arr[:,0]
print(col)

[1 4 7]


In [ ]:
#extract second row
row2=arr[1,:]
print(row2)

[4 5 6]


In [ ]:
#print an elent from array
print(arr[1,2])

6


In [ ]:
#basic indexing
arr=np.array([10,20,30,40,50])
print(arr[1])

20


In [ ]:
print(arr[-3])

30


In [ ]:
#subset indexing
print(arr[1:4])

[20 30 40]


In [ ]:
print(arr[arr>25])

[30 40 50]


In [ ]:
#horizontal joint
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#vertical joint
result=np.vstack((arr1,arr2))
print (result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#depth joint
result=np.dstack((arr1,arr2))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [ ]:
#splitting in numpy
arr=np.array([1,2,3,4,5,6])
result=np.split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
#splitting unequal parts
result=np.array_split(arr,4)
print(result)

[array([1, 2]), array([3, 4]), array([5]), array([6])]
