In [2]:
import numpy as np
a=np.array([10,20,30,40,50])
print("One dimensional array:",a)

One dimensional array: [10 20 30 40 50]


In [3]:
import numpy as np
a=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("Two dimensional array:",a)

Two dimensional array: [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [5]:
import numpy as np
a=np.zeros((3,5))
print("\n Array with all zeros:\n",a)


 Array with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
import numpy as np
d=np.random.random((3,3))
print("\n Random value:",d)


 Random value: [[0.87946757 0.63090292 0.82874805]
 [0.12252681 0.2624025  0.02962696]
 [0.7313993  0.87696721 0.11412588]]


In [7]:
import numpy as np
e=np.arange(0,10,1)
print("\n Range value :\n",e)


 Range value :
 [0 1 2 3 4 5 6 7 8 9]


In [8]:
import numpy as np
e=np.arange(0,10,5)
print("\n Range value :\n",e)


 Range value :
 [0 5]


In [9]:
import numpy as np
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape((4,3))
print("\n Original array:",arr)
print("\n Reshaped array:",newarr)


 Original array: [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

 Reshaped array: [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [1]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print("\n two dimensional array: ",arr)


 two dimensional array:  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [2]:
import numpy as np
arr=np.zeros((5,3))
print("\n array with all zeros:",arr)


 array with all zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
import numpy as np
arr=np.random.random((5,3))
print("\n array with random numbers:",arr)


 array with random numbers: [[0.17307998 0.03179676 0.58544019]
 [0.80912406 0.12119096 0.29269713]
 [0.77418531 0.56165481 0.9903929 ]
 [0.4062107  0.35003166 0.22948258]
 [0.94771824 0.72426057 0.6619044 ]]


In [4]:
import numpy as np
arr=np.arange(0,20,5)
print("\n range value:\n",arr)


 range value:
 [ 0  5 10 15]


In [2]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
newarr=arr.reshape((3,5))
print("\n original array:\n",arr)
print("\n reshaped array:\n",newarr)
print("\n No. of dimensions:",arr.ndim)
print("\n Shape of array:",arr.shape)
print("\n Array element type:",arr.dtype)


 original array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

 reshaped array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

 No. of dimensions: 2

 Shape of array: (5, 3)

 Array element type: int32


In [9]:

flat=arr.flatten()
print("Flattened array:\n",flat)

Flattened array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


NameError: name 'arr' is not defined

In [1]:
print("\n Array element type:",arr.dtype)

NameError: name 'arr' is not defined

In [4]:
newtype=arr.astype('f')
print("\n Convert array element\n",newtype)
print("datatype of converted array:\n",newtype.dtype)


 Convert array element
 [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]
datatype of converted array:
 float32


In [6]:
size=len(arr)
print("\n size of array:",arr.size)


 size of array: 15
